name: Build Kernel Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: smatyukevich/raspberry-pi-os-builder
    steps:
    - uses: actions/checkout@v2
    - run: make
