name: Build Kernel Image

on:
  push:
    branches: [ main ]
    tags:
    - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: smatyukevich/raspberry-pi-os-builder
    steps:
    - uses: actions/checkout@v2
    - run: make
    - uses: actions/upload-artifact@v2
      with:
        name: kernel8.img
        path: kernel8.img
    - uses: softprops/action-gh-release@v0.1.12
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: kernel8.img
